const mongoose = require('mongoose');

const BuildingsSchema = new mongoose.Schema({

    userEmail:{type: String},
    receiveUnitsArray: { type: Array },
    nameInInvoice: { type: String },
    lessorName: { type: String },
    adjective: { type: String },
    buildingType: { type: String },
    idNumber: { type: Number },
    expID: { type: Date },
    bank: { type: String },
    passPortNumber: { type: Number },
    expPassPort: { type: Date },
    nationality: { type: String },
    ibanNo: { type: Number },
    vatRegistrationNo: { type: Number },
    bankAccountNumber: { type: Number },
    tradeLicenseNo: { type: Number },
    buildingNameInArabic: { type: String },
    buildingNameInEnglish: { type: String },
    totalUnits: { type: Number },
    unitsPerFloor: { type: Number },
    parkings: { type: Number },
    roof: { type: Number },
    country: { type: String },
    city: { type: String },
    area: { type: String },
    mizan: { type: Number },
    plotArea: { type: Number },
    floor: { type: Number },
    buildingArea: { type: Number },
    electricityMeterNo: { type: Number },
    titleDeedNo: { type: Number },
    contractStartDate: { type: Date },
    investmentStructure: { type: String },
    gracePeriodFrom: { type: Date },
    contractEndDate: { type: Date },
    amount: { type: Number },
    gracePeriodTo: { type: Date },
    paymentScheduling: { type: String },
    name: { type: String },
    phoneNo: { type: Number },
    email: { type: String },
    type: { type: String },
    attachment: { type: String },

  },{timestamps:true});

mongoose.models={}
export default mongoose.model("Buildings", BuildingsSchema);